### ISSUE TITLE
TextureMode.PBR - PBR textures are not included

### ISSUE THREAD

**Issue by lvonasek** [HMS-Core/hms-3d-modeling-demo#12]
I tested object modeling with TextureMode.PBR:
``
            Modeling3dReconstructSetting setting = new Modeling3dReconstructSetting.Factory()
                    .setReconstructMode(Modeling3dReconstructConstants.ReconstructMode.PICTURE)
                    .setTextureMode(Modeling3dReconstructConstants.TextureMode.PBR)
                    .create();

            Modeling3dReconstructInitResult modeling3dReconstructInitResult;
            modeling3dReconstructInitResult = modeling3dReconstructEngine.initTask(setting);
```

When I download the reconstructed model there is diffuse texture only. I tested it with both OBJ and GLTF.

**Comment by Mike-mei** [comment]
Please change the download mode and try again, refer to this [document](https://developer.huawei.com/consumer/en/doc/development/graphics-Guides/reconstruct-engine-0000001156106863)

**Comment by coolleizhu** [comment]
You can only get diffuse texture because you are download in normal mode.

You can configure the download settings with Modeling3dReconstructDownloadConfig.Factory interface to get the expected result.

There is development guide here:  
[https://developer.huawei.com/consumer/en/doc/development/graphics-Guides/reconstruct-engine-0000001156106863#section58372254289](https://developer.huawei.com/consumer/en/doc/development/graphics-Guides/reconstruct-engine-0000001156106863#section58372254289)

You can find the download part in step 8.
